### ISSUE TITLE
Social Media Design | July 2017

### ISSUE THREAD

**Issue by nicolebash** [StudioBasham/Amazing-Beauty#1]
## Brief

Create social media post for Sharon, post on all platforms.

## Requirements

- [x] Design post
- [x] Review with Sharon
- [x] Post on Facebook & Instagram

**Comment by nicolebash** [comment]
**Copy on design:**

Goodbye Winter, Hello Summer!

**Social copy:**
Say goodbye to dry winter hair with our amazing Coconut hair care range. Once you've tried the Coconut range, you'll feel like summer again.

#VatikaNaturals #GreatHair #FeelsLikeSummer #AmazingBeauty

**Comment by nicolebash** [comment]
@Amazingbeauty1 please see my design below:

**Social copy (description on Facebook/Instagram)**
Say goodbye to dry winter hair with our amazing Coconut hair care range. Once you've tried the Coconut range, you'll feel like summer again.

#VatikaNaturals #GreatHair #FeelsLikeSummer #AmazingBeauty
<br />
![amazing-beauty-coconut-display](https://user-images.githubusercontent.com/30439770/28589987-c7619ae8-7180-11e7-9fcb-5ba50f570492.jpg)

**Comment by sharonpillay** [comment]
Love the ad! Thank you.Only addition is to add the word Tropical ..so it would read tropical coconut  on line 2 and 3.

**Comment by nicolebash** [comment]
Thanks @sharonpillay , I have also added your email address at the bottom of the text:

**Social copy (description on Facebook/Instagram)**
Say goodbye to dry winter hair with our amazing Tropical Coconut hair care range. Once you've tried the Tropical Coconut range, you'll feel like summer again.

Email us at order@amazingbeautyshop.co.za to get great hair.

#VatikaNaturals #GreatHair #FeelsLikeSummer #AmazingBeauty

**Comment by nicolebash** [comment]
I have scheduled the post to Facebook for tomorrow (27 July) morning at 10:00

<img width="626" alt="screen shot 2017-07-26 at 18 55 04" src="https://user-images.githubusercontent.com/30439770/28633437-165e798c-7234-11e7-8bb3-24c849d7159e.png">

**Comment by nicolebash** [comment]
I have scheduled the post for tomorrow (27 July) at 10:00 on instagram

![img_0232](https://user-images.githubusercontent.com/30439770/28634607-094aeace-7238-11e7-95c9-b7efb31386aa.PNG)
![img_0233](https://user-images.githubusercontent.com/30439770/28634608-094d8036-7238-11e7-8d76-f2496ccd0806.PNG)

**Comment by nicolebash** [comment]
<img width="350" alt="screen shot 2017-07-27 at 16 57 41" src="https://user-images.githubusercontent.com/30439770/28677129-e592ad82-72ec-11e7-90dc-8346eec91bc8.png">

<img width="350" alt="screen shot 2017-07-27 at 16 38 32" src="https://user-images.githubusercontent.com/30439770/28677075-bf520866-72ec-11e7-86fb-83b5845eb3d7.png">

I will close this issue.
