### ISSUE TITLE
Cover image | Facebook

### ISSUE THREAD

**Issue by nicolebash** [StudioBasham/Amazing-Beauty#5]
## Brief

Create a mobile safe cover image for Facebook for Sharon advertising free delivery to Cape Town.

## Requirements
- [x] Design
- [x] Review with Sharon
- [x] Post
- [x] Add to site via popup as well

**Comment by nicolebash** [comment]
@sharonpillay please see the free delivery cover image I've designed:

![free-delivery-facebook-banner](https://user-images.githubusercontent.com/30439770/30035289-ec9a132e-91a8-11e7-98ef-8c2115a63664.jpg)

**Comment by sharonpillay** [comment]
LOL This is brilliant!! LOVE IT:)) Thanks Nicole

**Comment by nicolebash** [comment]
Thanks Sharon! :) I'll schedule it for tomorrow morning at 10:00 on Facebook and add a pop up banner to the site.

**Comment by sharonpillay** [comment]
Ok awesome Great stuff !!

**Comment by nicolebash** [comment]
Implemented pop-up to site:

<img width="1270" alt="screen shot 2017-09-04 at 20 45 32" src="https://user-images.githubusercontent.com/30439770/30036284-0625369e-91b2-11e7-9d0a-b64f15c48242.png">

**Comment by nicolebash** [comment]
Cover image has been uodated on Facebook, I will close this ticket.

<img width="1066" alt="screen shot 2017-09-05 at 18 19 03" src="https://user-images.githubusercontent.com/30439770/30071380-c55b012e-9266-11e7-9890-89d78e92821d.png">
