### ISSUE TITLE
Display image | Week 1 | Facebook and instagram

### ISSUE THREAD

**Issue by nicolebash** [StudioBasham/Amazing-Beauty#6]
## Brief

Create combination package post design for Sharon.

## Requirement

- [x] Get highlight package and price from Sharon
- [x] Design
- [x] Review with Sharon
- [x] Draft post for Facebook, inform Sharon
- [x] Publish to instagram

**Comment by nicolebash** [comment]
Brief from Sharon:

**Package highlight**
 Almond shampoo (400 ml), Almond conditioner (400 ml), Almond oil (200 ml)

**Price**
Normal price = R34
Now = R300
Save R47 (25%)
Free delivery!
Only 10 available

**Comment by nicolebash** [comment]
![Image](https://i.imgur.com/yFzYpKA.jpg)

**Comment by nicolebash** [comment]
@sharonpillay please review the post (description and display image):


Get our limited range Almond package now and save 25%! Only 10 available.

Inbox us to order this special offer. Buy our Almond Shampoo (400 ml), Almond Conditioner (400 ml) and Almond Enriched Hair Oil (200 ml) for only R300, including free delivery!

#AmazingBeauty #AllNaturalBeauty #SpoilYourself
![almond-package-display-image](https://user-images.githubusercontent.com/30439770/30077368-eca904d2-927b-11e7-858d-aa3da6d236ec.jpg)

**Comment by sharonpillay** [comment]
Exciting... looks great thanks Nicole ;)

**Comment by nicolebash** [comment]
Offer scheduled to Facebook:

<img width="556" alt="screen shot 2017-09-05 at 21 13 27" src="https://user-images.githubusercontent.com/30439770/30079018-17c275a6-927f-11e7-9bd9-9faf05b23906.png">

**Comment by nicolebash** [comment]
Posted to instagram.
